### ISSUE TITLE
はてなブログのfeedを読み込めない

### ISSUE THREAD

**Issue by yuntan** [yuntan/mikutter-rss#1]
10個目以降のRSSソースについて，

```
notice: /home/yuntan/.mikutter/plugin/rss/fetch.rb:30:in `block (4 levels) in <top (required)>': got 10 entries for source 6
```

のログが流れない．タイムラインにも表示されない．

```
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
```

というログが流れているが関係あるかは不明．

**Comment by yuntan** [comment]
RSSソースの個数ではなく特定のサイトのRSSソースが原因であることが分かった．はてなブログのfeedを読み込もうとすると

```
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
```

が発生する．なぜか3つのソースに対し4回ログが流れる．

**Comment by yuntan** [comment]
はてなブログのfeedを読み込むと`feed.clean!`で

```
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
/home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:153: warning: regexp match /.../n against to UTF-8 string
ArgumentError: invalid byte sequence in UTF-8
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:135:in `block (2 levels) in dodgy_uri?'
```

が出た．

**Comment by yuntan** [comment]
`feed.clean!`を`rescue`すると

```
warning: /home/yuntan/.mikutter/plugin/rss/fetch.rb:28:in `rescue in block (4 levels) in <top (required)>': invalid byte sequence in UTF-8
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:135:in `block (2 levels) in dodgy_uri?'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:127:in `each'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:127:in `block in dodgy_uri?'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:126:in `each'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:126:in `dodgy_uri?'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:79:in `block (2 levels) in clean'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:78:in `reject!'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:78:in `block in clean'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:76:in `each'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/html-cleaner.rb:76:in `clean'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:109:in `block in clean!'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:108:in `each'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:108:in `clean!'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:113:in `block (2 levels) in clean!'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:113:in `collect'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:113:in `block in clean!'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:112:in `each'
from /home/yuntan/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/feed-normalizer-1.5.2/lib/structures.rb:112:in `clean!'
from /home/yuntan/.mikutter/plugin/rss/fetch.rb:26:in `block (4 levels) in <top (required)>'
notice: /home/yuntan/.mikutter/plugin/rss/fetch.rb:34:in `block (4 levels) in <top (required)>': got 30 entries for source 10
```

が出るが処理できた．
