### ISSUE TITLE
"接続が相手からリセットされました - SSL_connect"でmikutterがクラッシュする

### ISSUE THREAD

**Issue by yuntan** [yuntan/mikutter-rss#2]
```
error: {MIKUTTER_DIR}/core/serialthread.rb:83:in `rescue in block in new_thread': 接続が相手からリセットされました - SSL_connect
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/net/http.rb:996:in `connect'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:736:in `open'
from /tmp/.mount_mikutt1RTAbn/usr/lib/ruby/2.6.0/open-uri.rb:35:in `open'
from /home/yuntan/.mikutter/plugin/rss/fetch.rb:22:in `block (4 levels) in <top (required)>'
from {MIKUTTER_DIR}/core/serialthread.rb:70:in `block in new_thread'
notice: {MIKUTTER_DIR}/mikutter.rb:75:in `rescue in boot!': catch exception `SystemExit'
notice: {MIKUTTER_DIR}/mikutter.rb:77:in `rescue in boot!': => `SystemExit'
notice: {MIKUTTER_DIR}/mikutter.rb:109:in `rescue in <main>': catch SystemExit
```

**Comment by yuntan** [comment]
`open`で`Errno::ECONNRESET`例外が発生するのを`rescue`していなかったのが原因． 226390d839053ba9fd75f50b24e2546fa4303046 で対応済み．
